spring:
    application:
        name: fable-minds
    profiles:
        active: dev
    output:
        ansi:
            enabled: ALWAYS
jwt:
    secret: 0123456789abcdef0123456789abcdef
    expiration: 86400000
gemini:
    api-key: SUA_CHAVE_API_AQUI