spring:
    datasource:
        url: jdbc:postgresql://ep-snowy-boat-a4p9m5i9-pooler.us-east-1.aws.neon.tech/fabledb?sslmode=require
        username: root
        password: npg_F7Mpf2bdQyji
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 30000
            maximum-pool-size: 5
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
    level:
        org: 
        hibernate:
            SQL: DEBUG
            type:
            descriptor:
                sql:
                BasicBinder: TRACE
jwt:
    secret: 0123456789abcdef0123456789abcdef
    expiration: 86400000