# Configurações específicas para o perfil de teste
spring:
  # Configuração do DataSource para usar o banco de dados em memória H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  # Configuração do JPA e Hibernate para o ambiente de teste
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # A configuração mais importante para testes:
      # 'create-drop' cria o esquema do banco de dados no início da execução dos testes
      # e o destrói no final. Isso garante que cada execução de teste seja limpa e isolada.
      ddl-auto: create-drop
    show-sql: false # Desativa o log de SQL no console para manter a saída do teste limpa

  # Configuração da inicialização de scripts SQL
  sql:
    init:
      # 'never' desativa a execução automática de ficheiros como data.sql ou schema.sql.
      # Isto é crucial porque os nossos testes criam os seus próprios dados programaticamente
      # no método @BeforeEach, evitando conflitos.
      mode: never
